Update data.json
pagopa/io-services-metadata pull request #189
Opened 2020-12-12 22:24 UTC by thisisjp

- Added compatible methods FAQ

2020-12-12 22:36 UTC, Undermaken requested changes

2020-12-12 22:36 UTC, Undermaken commented on contextualhelp/data.json
> +                  "body": "Puoi partecipare al Cashback con:\n- carte di credito;\n- carte di debito su circuiti internazionali e su circuito PagoBANCOMAT;\n- carte prepagate;\n- le cosiddette carte
```suggestion
                  "body": "Puoi partecipare al Cashback con:\n- carte di credito;\n- carte di debito su circuiti internazionali e su circuito PagoBANCOMAT;\n- carte prepagate;\n- le cosiddette carte fedeltà, ovvero carte e app di pagamento connesse a circuiti privati e/o a spendibilità limitata (_esclusi, quindi, quelli solo per accumulo punti_);\n- app di pagamento, come ad esempio Satispay o BANCOMAT Pay;\n- altri sistemi di pagamento, come ad esempio Google Pay e Apple Pay (**sull'App IO a partire dal 2021**).\n\n**Nota bene**: All’avvio del Programma, alcune carte o app di pagamento che utilizzi potrebbero NON essere registrabili da subito, seppur inclusi nelle categorie di cui sopra, o potrebbero essere registrabili solo da un [canale alternativo a IO](https://io.italia.it/cashback/issuer/). Questo potrebbe dipendere dai tempi tecnici necessari per rendere operativi i metodi di pagamento elettronici nell’ambito del Cashback. [Verifica quali metodi di pagamento puoi già attivare per il Cashback](https://io.italia.it/metodi-pagamento/)."
```
is it a typo?

2020-12-13 00:09 UTC, thisisjp commented
it seems like a typo in the original source (IO Website). I'll inform the content owners ;)

2020-12-13 07:39 UTC, Undermaken approved these changes

2020-12-13 07:39 UTC, merged