ISP co-badge full abi list
pagopa/io-services-metadata pull request #308
Opened 2021-04-29 10:22 UTC by gammam

Added all ABI list managed by ISP co-badge service.
The following ABI are not in abi.json file

06325
05026
03186
06340* 
06260*
03309
02002

2021-04-29 10:26 UTC, fabriziofff requested changes
@gammam in order to pass the CI checks we need:
- Add the missing abi to the `abi.json` file
- The name should be the same

```
[01010] with name "BANCO DI NAPOLI S.P.A.O" should be "BANCO DI NAPOLI S.P.A."
abi 02002 cannot have an empty name
abi 03309 cannot have an empty name
abi 06260 cannot have an empty name
[06340] with name "" should be "CASSA DI RISPARMIO DEL FRIULI VENEZIA GIULIA"
abi 03186 cannot have an empty name
abi 05026 cannot have an empty name
abi 06325 cannot have an empty name
```

2021-04-29 13:16 UTC, thisisjp approved these changes
I've added the missing bank names

2021-04-29 13:16 UTC, thisisjp commented on status/cobadgeServices.json
> +        "name": ""
```suggestion
        "name": "Cassa di Risparmio di Pistoia e della Lucchesia"
```

2021-04-29 13:16 UTC, thisisjp commented on status/cobadgeServices.json
> +        "name": ""
```suggestion
        "name": "Cassa di Risparmio di Tortona S.p.A."
```

2021-04-29 13:16 UTC, thisisjp commented on status/cobadgeServices.json
> +        "name": ""
```suggestion
        "name": "BPU Banca - Banche Popolari Unite"
```

2021-04-29 13:16 UTC, thisisjp commented on status/cobadgeServices.json
> +        "name": ""
```suggestion
        "name": "B@nca 24-7 S.p.a."
```

2021-04-29 13:16 UTC, thisisjp commented on status/cobadgeServices.json
> +        "name": ""
```suggestion
        "name": "Banca Infrastrutture Innovazione e Sviluppo S.p.A."
```

2021-04-29 13:16 UTC, thisisjp commented on status/cobadgeServices.json
> +        "name": ""
```suggestion
        "name": "Banca Commerciale Italiana"
```

2021-04-29 13:23 UTC, fabriziofff requested changes

2021-04-29 13:23 UTC, fabriziofff commented on status/cobadgeServices.json
> +        "name": "BANCO DI NAPOLI S.P.A"
```suggestion
        "name": "BANCO DI NAPOLI S.P.A."
```

2021-04-30 07:58 UTC, fabriziofff approved these changes

2021-04-30 07:58 UTC, merged