Contextual Help in COVID-19 screens
pagopa/io-services-metadata pull request #349
Opened 2021-06-09 17:19 UTC by Loreau

2021-06-09 17:32 UTC, thisisjp requested changes

2021-06-09 17:32 UTC, thisisjp commented on contextualhelp/data.json
> +                  "body": "No, su IO vengono inviati esclusivamente i certificati relativi all'utente loggato nell'app attraverso le proprie credenziali SPID o CIE. Puoi comunque ottenere i certifica
```suggestion
                  "body": "No, su IO vengono inviati esclusivamente i certificati relativi all'utente autenticato nell'app attraverso le proprie credenziali SPID o CIE. Puoi comunque ottenere i certificati relativi ai tuoi familiari attraverso gli altri canali disponibili. Per saperne di più vai sul sito dedicato [dgc.gov.it](https://www.dgc.gov.it/)"
```

2021-06-09 17:32 UTC, thisisjp commented on contextualhelp/data.json
> +                  "body": "No, su IO vengono inviati esclusivamente i certificati relativi all'utente loggato nell'app attraverso le proprie credenziali SPID o CIE. Puoi comunque ottenere i certifica
```suggestion
                  "body": "No, su IO vengono inviati esclusivamente i certificati relativi all'utente autenticato nell'app attraverso le proprie credenziali SPID o CIE. Puoi comunque ottenere i certificati relativi ai tuoi familiari attraverso gli altri canali disponibili. Per saperne di più vai sul sito dedicato [dgc.gov.it](https://www.dgc.gov.it/)"
```

2021-06-17 13:39 UTC, Undermaken approved these changes

2021-06-17 20:50 UTC, closed without merging