feat: [IOBP-964] Add zendesk payment subcategories
pagopa/io-services-metadata pull request #892
Opened 2024-12-09 09:36 UTC by LeleDallas

> [!Note]
> To test this PR take a look [here](https://github.com/pagopa/io-dev-api-server/pull/446)

## Short description
This pull request introduces a new configuration for managing payment subcategories and their statuses. The main changes include the addition of a new JSON file for payment mappings, updates to existing JSON configurations, and modifications to the schema definitions.

## List of changes proposed in this pull request
- Added new subcategory definitions under `zendeskSubCategories` for various payment-related scenarios.
- Added a new `ZendeskPaymentMap` object definition to map payment methods with the correct Zendesk subcategories, including required fields and properties for different payment statuses.
- Added documentation for the new `paymentMap.json` file, which contains mappings between subcategories and payment statuses.

2024-12-09 11:40 UTC, Hantex9 requested changes

2024-12-09 11:40 UTC, Hantex9 commented on assistanceTools/paymentMap.json
What do you think about restructuring this instead of having a single `paymentMap.json` file?

We could organize it into folders under the `assistanceTools` directory. For example, we could have a `payments` subfolder, and within it, include a JSON file named something like `zendeskOutcomeMapping.json`. 

This structure might improve clarity and maintainability by grouping related files logically. Let me know your thoughts!

2024-12-09 11:52 UTC, LeleDallas commented on assistanceTools/paymentMap.json
Make sense to me! I also need to create a similar feature for handling receipts

2024-12-09 12:04 UTC, Hantex9 commented on assistanceTools/paymentMap.json
In this case, instead of creating multiple files, what do you think to handle them adding one layer to the top of the structure? Here is an example:

```json
{
    "payments": {
      "subcategoryId": "29473336574609",
      "subcategories": {
          "pagamenti_pagopa_in_corso": [
              "PAYMENT_ONGOING"
          ],
          "pagamenti_pagopa_blocco": [],
          "pagamenti_pagopa_info_stato": [],
          "pagamenti_pagopa_altro_problema": []
      }
    },
    "receipts": {
      "subcategoryId": "7777777",
      "subcategories": {
          "pagamenti_pagopa_in_corso": [
              "TEST"
          ],
          "pagamenti_pagopa_blocco": [],
      }
    },
}
```

2024-12-09 12:24 UTC, LeleDallas commented on assistanceTools/paymentMap.json
Sounds good!

2024-12-09 14:36 UTC, Hantex9 requested changes

2024-12-10 09:12 UTC, Hantex9 approved these changes
LGTM! 🚀

2024-12-10 10:23 UTC, merged